[workspace]
members = [
  "decoder",
  "decoder/defmt-json-schema",
  "defmt",
  "macros",
  "parser",
  "print",
  "qemu-run",
  "xtask",
]
exclude = [ "firmware/*" ]


[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 3
overflow-checks = false
