name: CI

on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]
  schedule:
    # runs 1 min after 2 or 1 AM (summer/winter) berlin time
    - cron: "1 0 * * *"

env:
  CARGO_TERM_COLOR: always
  NO_STD_TARGET: thumbv7em-none-eabi # firmware uses atomics
  QEMU_TARGET: thumbv7m-none-eabi

jobs:
  host:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Use the latest stable release
        run: rustup update stable && rustup default stable
      - name: Install C libraries for tooling on ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install libudev-dev libusb-1.0-0-dev
      - name: Check that all crates that can be compiled for the host build, check that defmt compiles with different features, run all unit tests on the host
        run: cargo xtask -d test-host

  cross:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use the latest stable release
        run: rustup update stable && rustup default stable
      - name: Install NO_STD_TARGET
        run: rustup target add ${{ env.NO_STD_TARGET }}
      - name: Install Rust targets, build defmt crates for no_std targets, build defmt dependent crates for cortex-m targets, build panic-probe with different features
        run: cargo xtask test-cross

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Use the latest stable release
        run: rustup update stable && rustup default stable
      - name: Run rustfmt & clippy
        run: cargo xtask test-lint

  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use the latest stable release
        run: rustup update stable && rustup default stable
      - name: Install Rust stable, run all UI tests on the host
        run: cargo xtask test-ui

  mdbook:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # as of 2021-04 github SIGKILLs us on macos for unknown reasons (possible OOM)
          # - macOS-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Use the latest stable release
        run: rustup update stable && rustup default stable
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: latest
      - name: Run book tests
        run: cargo xtask test-book

  qemu-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use the latest stable release
        run: rustup update stable && rustup default stable
      - name: Install QEMU_TARGET
        run: rustup target add ${{ env.QEMU_TARGET }}
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install qemu qemu-system-arm
      - name: Run QEMU snapshot tests
        run: cargo xtask test-snapshot

  backcompat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use the latest stable release
        run: rustup update stable && rustup default stable
      - name: Install QEMU_TARGET
        run: rustup target add ${{ env.QEMU_TARGET }}
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install qemu qemu-system-arm
      - name: Run backward compatibility test
        run: cargo xtask test-backcompat

  # Refs: https://github.com/rust-lang/crater/blob/9ab6f9697c901c4a44025cf0a39b73ad5b37d198/.github/workflows/bors.yml#L125-L149
  # bors.tech integration
  ci-success:
    name: ci
    if: ${{ success() }}
    needs:
      - host
      - cross
      - lint
      - mdbook
      - qemu-snapshot
      - backcompat
      - ui
    runs-on: ubuntu-20.04
    steps:
      - name: CI succeeded
        run: exit 0
